index:
    path: /
    controller: App\Controller\HomeController::index

home:
    path: /home
    controller: App\Controller\HomeController::index

patchBook:
    path: /book/{id}
    controller: App\Controller\BookController::patchBook
    methods: [PATCH]

book:
    path: /book
    controller: App\Controller\BookController::index

postBook:
    path: /postBook
    controller: App\Controller\BookController::postBook

getBook:
        path: /getBook
        controller: App\Controller\BookController::getBook

bookConfirm:
    path: /bookConfirm/{id}
    controller: App\Controller\BookController::bookConfirm

showMail:
    path: /showMail
    controller: App\Controller\ShowMailController::index